name: Release APK on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble Release
        run: |
          ./gradlew :app:assembleRelease --console=plain

      - name: Compute SHA256
        run: |
          cd app/build/outputs/apk/release
          sha256sum app-release.apk > app-release.apk.sha256.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release.apk.sha256.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release.apk.sha256.txt
          body_path: docs/release-notes/1.0.2.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
